name: PermAnnouncements2
version: ${project.version}
main: me.linoxgh.permannouncements2.PermAnnouncements2
api-version: 1.16
authors: [ LinoxGH ]
description: Player-specific announcements based on permissions.

commands:
  permannouncements2:
    description: "Main command for PermAnnouncements2 plugin."
    usage: "/permannouncements2 help"
    permission: permannouncements2.main
    permission-message: "ยง4You do not have enough permission to use this command."
    aliases: [ permannouncements, announcements, pa2, pa ]

permissions:
  permannouncements2.admin:
    description: "Admin permission node for all adding, removing and changing configs."
    default: op
    children: [ permannouncements2.info, permannouncements2.config, permannouncements2.list, permannouncements2.add, permannouncements2.remove, permannouncements2.edit, permannouncements2.refresh, permannouncements2.reload ]
  permannouncements2.info:
    description: "Permission node responsible for viewing configs in-game."
    default: op
    children: [ permannouncements2.main ]
  permannouncements2.config:
    description: "Permission node responsible for changing configs in-game."
    default: op
    children: [ permannouncements2.main ]
  permannouncements2.list:
    description: "Permission node responsible for listing announcements."
    default: op
    children: [ permannouncements2.main ]
  permannouncements2.add:
    description: "Permission node responsible for adding announcements."
    default: op
    children: [ permannouncements2.main ]
  permannouncements2.remove:
    description: "Permission node responsible for removing announcements."
    default: op
    children: [ permannouncements2.main ]
  permannouncements2.edit:
    description: "Permission node responsible for editing announcements."
    default: op
    children: [ permannouncements2.main ]
  permannouncements2.refresh:
    description: "Permission node responsible for refreshing the announcement task."
    default: op
    children: [ permannouncements2.main ]
  permannouncements2.reload:
    description: "Permission node responsible for reloading the plugin configs and announcements."
    default: op
    children: [ permannouncements2.main ]

  permannouncements2.main:
    description: "Main permission node for /permannouncements2 command."
    default: op